version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    build: ./db
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Pa$$w0rd"
      MYSQL_PASSWORD: "Pa$$w0rd"
#    volumes:
#        - ./db-container/db_seed.sql:/data/application/db_seed.sql
#    volumes:
#      - ./db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
