version: "2"
services:
  app:
    image: flaskapp
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: flaskdb
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "Pa$$w0rd"
      MYSQL_ROOT_USER: "root"
      MYSQL_DATABASE: "mydb"
      MYSQL_DATABASE_HOST: "%"
    volumes:
        - ./db-container/db_seed.sql:/data/application/db_seed.sql
#    volumes:
#      - ./db_seed.sql:/docker-entrypoint-initdb.d/db_seed.sql
